name: Telepresence with GitHub Actions Demo
on: [push]
jobs:
  PlaceHolder:
    runs-on: centos-latest
    env:
      COLOR: blue
      AMBASSADOR_SERVICE_IP: $your.service.ip 
    steps:
      - name: capture test value
        run: output=`curl "-s " $AMBASSADOR_SERVICE_IP | grep 'green'`
      -name: ensure service is running locally
          - run: |
                 if ["$output" != ""]; then
                    echo "The service is not running in the build environment"     
                    exit 1
                 fi
