name: Telepresence with GitHub Actions Demo
on: [push]
jobs:
  PlaceHolder:
    runs-on: centos-latest
    env:
      COLOR: blue
      AMBASSADOR_SERVICE_IP: $your.service.ip 
    steps:
      - name: ensure service is running locally
          - run: |
                 if ["$output" != ""]; then
                    echo "The service is not running in the build environment"     
                    exit 1
                 fi

      - name: Telepresence connect and intercept
        - run: telepresence connect
        - run: telepresence intercept dataprocessingservice --port 3000

      - name: capture test value
        run: result=$(curl -s "http://localhost:3000/color")
           # strip the tick marks off the string in $output
        run: result=$(echo $result | tr -d '///"')  

      - name: compare test value
        run: |
             if ["$output" != $result"]; then
                echo "Values do not match, stopping pipelinet"     
                exit 1
             fi        
